AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda Microservices

Globals:
  Function:
    Timeout: 360
    Tracing: Active
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.9
    Architectures:
      - x86_64

Resources:
  Api:
    Type: AWS::Serverless::Api
    Name: !Sub api-microservice
    Properties:
      TracingEnabled: true
      StageName: !Ref Environment
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'*'"
        AllowHeaders: "'*'"

  UsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/users
      FunctionName: !Sub users
      Description: !Sub Users microservice 
      Events:
        UsersCrud:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users
            Method: ANY